#!/usr/bin/env bash
#Install nginx on
apt-get -y update
apt-get -y install nginx

ufw allow 'Nginx HTTP'

echo "Hello World" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a \\tlocation /redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4/ permanent; }' /etc/nginx/sites-available/default

sudo chown $USER:$USER /var/www/html
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default

service nginx restart
