#!/bin/bash
chown vincent:staff *
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
14-change_owner_and_group [unix] (00:59 01/01/1970)               0,0-1 All
"14-change_owner_and_group" [New]

