#!/usr/bin/env bash
#This script Indefinitely writes I am alive! to the file /tmp/my_process
#the program pause for 2 seconds in between every iteration

while true
do
    echo "I am alive!" > /tmp/my_process
    sleep 2
done